[project]
name = "sse-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp>=1.3.0",
    "starlette>=0.46.0",
    "uvicorn>=0.34.0",
]
[tool.setuptools]
py-modules = ["terminal_server_sse"]